### ISSUE TITLE
[FE] Show orders to non buyers

### ISSUE THREAD

**Issue by devey** [rysk-finance/dynamic-hedging#311]
Make sure that even if user is not buyer it is possible to see an order details, to allow team to easily double check that values are correct.

```tsx
// OTCPageContent.tsx
useEffect(() => {
    if (account && order) {
      if (account.toLowerCase() !== order.buyer.toLowerCase()) {
        setError(`❌ Please connect with account ${order.buyer}`);
      }
    }
  }, [account, order]);
```

**Comment by swarna1101** [comment]
To allow users to view order details even if they are not the buyer, you can modify the code you provided to remove the check for whether the user's account is the same as the buyer's account.

```tsx
// OTCPageContent.tsx
useEffect(() => {
    if (order) {
      // No longer checking whether the user's account is the same as the buyer's account
    }
  }, [account, order]);
```
