### ISSUE TITLE
Implement Table Prices

### ISSUE THREAD

**Issue by devey** [rysk-finance/dynamic-hedging#326]
- [x] deploy Pricer to testnet
- [x] use contract to retrieve quotes
- [x] use quotes to compute `IV` in front-end

**Comment by devey** [comment]
waiting on #333

**Comment by MeanBoyCousin** [comment]
> waiting on #333

With this closed, can we close this issue?

**Comment by devey** [comment]
@MeanBoyCousin it should close automatically when #327 gets merged

**Comment by MeanBoyCousin** [comment]
Hmm, looks like it didn't. Will do so now. 👍
