### ISSUE TITLE
Set up codecov

### ISSUE THREAD

**Issue by MeanBoyCousin** [rysk-finance/dynamic-hedging#345]
Setting up Codecov reporting would be helpful for ensuring coverage stays up and keeps us publicly accountable via badges.

Codecov has a free tier (max 5 users, max 250 runs per month). This should be fine as not everyone will need access and we can use a custom workflow to trigger coverage runs only when a specific label is added to a PR. This could be done once the review is complete and the PR is ready to minimise runs being used up with each commit to a PR.

We can start off with just the hardhat tests and eventually add in other CI runs for other areas like the front end.

**Comment by kjr217** [comment]
Yeah great idea, i run it manually anyway but I dont think it would be hard to add onto our CI flow for smart contracts
