### ISSUE TITLE
Change "expired" tab in dashboard for options

### ISSUE THREAD

**Issue by ugolino** [rysk-finance/dynamic-hedging#358]
Some of the alpha traders had issues easily finding the expired options to redeem them after they expired.

Might be worth re-design the table, tabs. 

I don't have strong suggestions on how to make that more visible. Feel free to propose ideas

<img width="1868" alt="Screenshot 2023-01-23 at 3 44 56 PM" src="https://user-images.githubusercontent.com/8145692/214068436-f4350b6b-9367-4243-9c65-ac274cdbb666.png">
<img width="1851" alt="Screenshot 2023-01-23 at 3 45 04 PM" src="https://user-images.githubusercontent.com/8145692/214068467-57052c29-6943-49f7-8f01-eddbb26af7e8.png">

**Comment by kjr217** [comment]
My thought toi

**Comment by ugolino** [comment]
yh. it makes sense to me.

Go for it and we will test it next weeks !
