### ISSUE TITLE
Show user position in trading table

### ISSUE THREAD

**Issue by devey** [rysk-finance/dynamic-hedging#361]
The expiry table should highlight if they own positions in that option for that expiry (similar to Deribit).

**Comment by MeanBoyCousin** [comment]
Have made a start on this in [this PR.](https://github.com/rysk-finance/dynamic-hedging/pull/413)

Works for longs but pending works for getting short positions.

**Comment by devey** [comment]
missing short here, right @MeanBoyCousin ?

**Comment by MeanBoyCousin** [comment]
Yes, currently the work I have only handled long positions, pending your work on the graph. We can tie up on a call once this is in place and work out the best way to query for both. I imagine that'll be part of a larger call overall to discus upgrades to all the querying and state management. Going to make a start on some of that this week.

**Comment by devey** [comment]
I'd say this is done, just need to make sure we adjust `POS` on trading table considering `longPositions` and `shortPositions`.
