### ISSUE TITLE
Show fees and options number impact

### ISSUE THREAD

**Issue by devey** [rysk-finance/dynamic-hedging#365]
User must be able to see the quote price for an option which should include the premium and the fees, they should be able to see how changing the number of options on their purchase will impact the price they must pay.

in the table we can show these together but in the option details under it we can show price + fees split.
in the same section we can show price difference based on how many options user wants to buy or sell.

**Comment by devey** [comment]
this is the same (besides a different parameter) for both buying and selling

**Comment by MeanBoyCousin** [comment]
Closing as this is handled in the most recent UI works.
