### ISSUE TITLE
Collateral setup for selling

### ISSUE THREAD

**Issue by devey** [rysk-finance/dynamic-hedging#367]
User should be able to select the collateral asset they would like to use to create the short position
User should be able to select the amount of collateral they would like to put up and should be shown guidance on a sensible amount.
User should be shown the exact price at which their position will get liquidated given a collateral amount they provide.

**Comment by devey** [comment]
you can get minimum margin requirement from  [`MarginCalculator` contract](https://github.com/rysk-finance/dynamic-hedging/blob/rysk-alpha/packages/contracts/contracts/packages/opyn/core/MarginCalculator.sol#L322) and multiply by 1.x to give user an estimate. User should still be able to put more than advised.

**Comment by devey** [comment]
@ugolino if you could link to the reference implementation here for getting liquidation price, open vault positions and collateral management that would be great, thanks.

**Comment by ugolino** [comment]
on the vault health, liquidation price we can use something like this: 

https://github.com/rysk-finance/gamma-portal/blob/199e09ee927f7aa6064c191680c8dcefc35bca4f/src/pages/Protocol/Liquidation/index.tsx#L152

Ideally we should use the params from opyn SC to reverse eng liquidation price. As an example here is the spot shock value:

https://github.com/rysk-finance/dynamic-hedging/blob/646c5b818387d7c3317897f7b848f262061007f3/packages/contracts/contracts/packages/opyn/core/MarginCalculator.sol#L289

Later I will make a more detailed explanation on how to reverse eng that

**Comment by devey** [comment]
Missing option to pick collateral
