### ISSUE TITLE
Allow to see all expiries in one view

### ISSUE THREAD

**Issue by devey** [rysk-finance/dynamic-hedging#380]
Instead of having the user go through all of the expiries to find a choice, they might want to have an overall glance of all expiries to be able to quickly spot what they are looking for (ex. arbitrage opportunity).

**Comment by MeanBoyCousin** [comment]
I need to follow what is meant by this. Do you have an example of what you had in mind?

**Comment by devey** [comment]
@MeanBoyCousin yeah, currently you go to the date you want to see expiry for but some users might want to just be able able to sell all dates and expiries in one screen:

[TABLE]
[date1]
[expiries1]
[date2]
[expiries2]
[date3]
[expiries3]

**Comment by MeanBoyCousin** [comment]
Oh, I see. That'd be a lot of data to fit on one screen. I guess we could add this later as a switch that flips the view from its current form to one as described above. We'd need to get pre-fetching and state management sorted for the whole chain first though or it'd be painfully slow.

Makes sense as follow up work to MVP.

**Comment by devey** [comment]
@MeanBoyCousin sounds good. I wrote it down as it came up in a meeting but I agree that is not a priority until other parts are sorted out.
