### ISSUE TITLE
Trading documentation

### ISSUE THREAD

**Issue by devey** [rysk-finance/dynamic-hedging#381]
To avoid confusion for user we might want to write down a description of how the trading process works and the steps involved in it.

**Comment by MeanBoyCousin** [comment]
Might also be good to build in a break-even, profit/loss simulator for the user to test scenarios. Mainly "nice to have" but would be good as a fast follow to the MVP.

**Comment by MeanBoyCousin** [comment]
https://www.npmjs.com/package/react-joyride

**Comment by MeanBoyCousin** [comment]
@ugolino Do you think this is needed for MVP/trading comp? I'm leaning towards no but want your clarity on expectations.

**Comment by devey** [comment]
@MeanBoyCousin created ux steps to explain platform
