### ISSUE TITLE
Use contract for getting IV

### ISSUE THREAD

**Issue by devey** [rysk-finance/dynamic-hedging#382]
Currently computing this in the front-end but there are contract methods for doing this. Also helps removing lots of logic from front-end.

- [getImpliedVolatility(isPut, underlyingPrice (e18), strikePrice (e18), expiration)](https://github.com/rysk-finance/dynamic-hedging/blob/rysk-beyond/packages/contracts/contracts/VolatilityFeed.sol)

**Comment by MeanBoyCousin** [comment]
Might be better to use the way we are currently doing it to avoid additional network requests. Unless we can move this into the graph?

**Comment by devey** [comment]
@MeanBoyCousin can't be moved to The Graph due to relying on `underlyingPrice` which is constantly changing

**Comment by MeanBoyCousin** [comment]
Then probably best to stick with the front-end computation, although we might want to audit the functionality. The contract call's in those functions could be extracted into global state and then we can fetch that data before the user needs it.

**Comment by devey** [comment]
We keep this on front-end for MVP.
