### ISSUE TITLE
Collateral vault health for selling

### ISSUE THREAD

**Issue by devey** [rysk-finance/dynamic-hedging#385]
In case user is opening a vault for creating `oToken` to sell to the `DHV` then we should retrieve users' collateral health and take that into account if user has already deposited collateral (for example if users position is healthy they might need to deposit less for the sell action they are about to send).

We should also allow users to change collateral of open position under dashboard (but this should be in another issue).

**Comment by devey** [comment]
@kjr217 did I get this correctly?

**Comment by kjr217** [comment]
Correct, as long as when you are referring to health factor you mean for the same vault where they are doing the mint action from

**Comment by devey** [comment]
collateral adjustment is done but we are still not taking account of vault health when going increasing a short position
