### ISSUE TITLE
Allow user to adjust position collateral

### ISSUE THREAD

**Issue by devey** [rysk-finance/dynamic-hedging#386]
Once a position starts moving user might want to have more or less collateral backing the position so we should allow them to see current health and adjust it.

**Comment by devey** [comment]
@ugolino @MeanBoyCousin you think this should this be under `/dashboard` options or under trading table?

**Comment by ugolino** [comment]
I think so,

Feel is better t have this under dashboard ideally with a recap of the positions.

For example how many positions are safe, into warning, in a dangerous zone or liquidated

**Comment by ugolino** [comment]
maybe if a position is warning or dangerous we can add that on the table like a small icon to show there is a risk

**Comment by MeanBoyCousin** [comment]
Yeah, agree with dashboard. I think the positions table rows will most likely turn into an accordion where we can store info such as this and potentially charts on break-even and P/L.

**Comment by devey** [comment]
gonna tackle this using same flow of modal we have for buying and selling :)
