### ISSUE TITLE
Allow user to close position

### ISSUE THREAD

**Issue by devey** [rysk-finance/dynamic-hedging#387]
This is self explanatory but just worth mentioning that `operate` call is similar to user selling back tokens to `DHV`. Only difference should be in action type (instead of `2` we use `actionType: 3`)

**Comment by MeanBoyCousin** [comment]
Now that I have re-worked the options table in the dashboard, it should be pretty simple to just replace the text with a button for any position that is still open.

**Comment by devey** [comment]
First comes #350
