### ISSUE TITLE
Beyond Extra

### ISSUE THREAD

**Issue by devey** [rysk-finance/dynamic-hedging#388]
This is a list of things that are not deemed necessary but would be nice to have after finishing the [basic version](https://github.com/orgs/rysk-finance/projects/1/views/2) of Beyond's trading front-end.

- [ ] simplified trading view: some users might want to have an easier interface to trade (versus a full trading table). They might just want to be asked if they thinks underlying is going up or down and set the amounts (without the selling side as that goes beyond Options 101 user).
- [x] Show to users our `netDhvExposure` (how many contracts of this series the DHV is already exposed to. e18. negative if net short);  this would give them a tool for their strategy decision. There is a function in `alphaPortfolioValuesFeed` to get exposure by passing `oHash` of the option.

**Comment by MeanBoyCousin** [comment]
`netDhvExposure` has been included in the MVP.

**Comment by MeanBoyCousin** [comment]
Closing as there is another issue for the only remaining point.
