### ISSUE TITLE
Fix user vault tooltips

### ISSUE THREAD

**Issue by devey** [rysk-finance/dynamic-hedging#389]
also just checked and seems like these tooltips are broken in `rysk-alpha`, going to open an issue

_Originally posted by @devey in https://github.com/rysk-finance/dynamic-hedging/pull/290#discussion_r1096563456_

**Comment by MeanBoyCousin** [comment]
I'd like to try and get rid of tooltips as possible ideally. Hidden content is just plain bad UX. 👍
