### ISSUE TITLE
Trades not loading

### ISSUE THREAD

**Issue by thegeronimo** [rysk-finance/dynamic-hedging#417]
<img width="1359" alt="Screen Shot 2023-02-20 at 9 39 44 AM" src="https://user-images.githubusercontent.com/59147332/220136168-12c1b072-30a3-4b0e-bcab-5dde2ee04cde.png">

**Comment by MeanBoyCousin** [comment]
@thegeronimo Is this still an issue for you? I'm thinking this was likely just a temporary issue whilst the graph was being updated. There are no distinct Sentry errors related to this as persistent so I'd like to close if it's no longer an issue.
