### ISSUE TITLE
ABI Export Flow

### ISSUE THREAD

**Issue by devey** [rysk-finance/dynamic-hedging#424]
Some ABIs are `json` files with more than 40k lines and it is overkill to copy over the whole file considering we are anyway in a monorepo and the front-end only needs the one that are being interacted with.

Find a way, [using `jq` vielleicht](https://github.com/rysk-finance/dynamic-hedging/pull/395#discussion_r1107458210), to extract only necessary elements.

**Comment by MeanBoyCousin** [comment]
Happy to dig into this in more detail. We can start with the small chunks we need and then expand the script as we need access to more of the ABI. We can also stop copying over the `json` files once we remove all reliance on them via the old hooks.
